name: mikuplay
description: "A new Flutter project for MikuPlay Application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0' # Sesuaikan dengan versi Flutter SDK di laptopmu

dependencies:
  flutter:
    sdk: flutter

  # Navigasi
  go_router: ^13.2.0

  # Google Sign In
  google_sign_in: ^6.2.1

  # Font Inter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_mikuplay.png"
  adaptive_icon_background: "#0A0B2E"
  adaptive_icon_foreground: "assets/images/logo_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/