// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfcdbOw4-_I1CygCEPjdayyTWQqit8gpA',
    appId: '1:23316546507:web:0faae477ff20836d39ec4e',
    messagingSenderId: '23316546507',
    projectId: 'mikuplay-2470a',
    authDomain: 'mikuplay-2470a.firebaseapp.com',
    storageBucket: 'mikuplay-2470a.firebasestorage.app',
    measurementId: 'G-C65GVKJKP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8dJLw36aHw_AgPMPXklHhmHWU0yohQFM',
    appId: '1:23316546507:android:bc1b8b64c0071d9639ec4e',
    messagingSenderId: '23316546507',
    projectId: 'mikuplay-2470a',
    storageBucket: 'mikuplay-2470a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzBDhsmwCOcaJTDtW_VY22AIhgnOZ0RCQ',
    appId: '1:23316546507:ios:0418246286d0459739ec4e',
    messagingSenderId: '23316546507',
    projectId: 'mikuplay-2470a',
    storageBucket: 'mikuplay-2470a.firebasestorage.app',
    iosBundleId: 'com.example.mikuplay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzBDhsmwCOcaJTDtW_VY22AIhgnOZ0RCQ',
    appId: '1:23316546507:ios:0418246286d0459739ec4e',
    messagingSenderId: '23316546507',
    projectId: 'mikuplay-2470a',
    storageBucket: 'mikuplay-2470a.firebasestorage.app',
    iosBundleId: 'com.example.mikuplay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfcdbOw4-_I1CygCEPjdayyTWQqit8gpA',
    appId: '1:23316546507:web:c7195db7466294bf39ec4e',
    messagingSenderId: '23316546507',
    projectId: 'mikuplay-2470a',
    authDomain: 'mikuplay-2470a.firebaseapp.com',
    storageBucket: 'mikuplay-2470a.firebasestorage.app',
    measurementId: 'G-19PF3V91JJ',
  );

}